### ISSUE TITLE
Change Counseling Service Attribution in Treefooter

### ISSUE THREAD

**Issue by code-IM-perfect** [code-IM-perfect/student-search#1]
The attribution to the Counseling Service on the Treefooter when viewing the family tree simply says 

**"data by CS"**

This is a very non specific message, which can be misleading and can be misinterpreted easily, I suggest this be changed to-

**"The Family Tree provided by Institute Counseling Service IITK"**

Current Footer-
![image](https://github.com/user-attachments/assets/be20236a-fafc-402e-b8b2-ae7cb5014806)

**Comment by its-me-yps** [comment]
Hey "where exactly is the footer" ?
I am trying to resolve the issue and would make a PR soon.

**Comment by code-IM-perfect** [comment]
The file of interest is on `components/Treefooter.js`

**Comment by code-IM-perfect** [comment]
Fixed in #2
